# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile2you' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile2you
pod 'Alamofire', '~> 5.2'

  target 'mobile2youTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile2youUITests' do
    # Pods for testing
  end

end
